version: '3.8'
services:
  web:
    container_name: ollama-chat-ui
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5171:5173"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./index.html:/app/index.html
      - ./vite.config.ts:/app/vite.config.ts
      - ./tsconfig.json:/app/tsconfig.json
      - ./tsconfig.app.json:/app/tsconfig.app.json
      - ./tsconfig.node.json:/app/tsconfig.node.json
      - ./tailwind.config.js:/app/tailwind.config.js
      - ./postcss.config.js:/app/postcss.config.js
      - ./.env:/app/.env
      - /app/node_modules
    environment:
      - VITE_HUGGINGFACE_TOKEN=${VITE_HUGGINGFACE_TOKEN}
      - VITE_OLLAMA_API_URL=${VITE_OLLAMA_API_URL:-http://localhost:11434}
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    command: npm run dev -- --host