version: "3.8"
services:
  web:
    container_name: ollama-chat-ui
    build: .
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      - VITE_OLLAMA_API_URL=${VITE_OLLAMA_API_URL}
    command: npm run dev -- --host
